export const SYSTEM_PACKAGE_ORDER = {
    FREE: 1,
    PRO: 2,
    PLUS: 3,
}

export const PACKAGE_FEATURE_CODES = [
    'NOTE_LIMIT',
    'DEVICE_LIMIT',
    'AI_NOTE_FORMAT',
    'DOCUMENT_UPLOAD',
    'TAG_SUBJECT',
    'CHECKLIST_BASIC',
    'AI_SUMMARY_BASIC',
    'AI_SUMMARY_ADVANCED',
    'AI_CHAT',
    'AI_ANALYZE',
    'AI_AUDIO',
    'EXTRACT_SCHEDULE',
    'DEADLINE_MANAGEMENT',
    'PRIORITY_SUGGESTION',
    'AI_FLASHCARD',
    'EXPORT_FILE',
    'TEAM_WORK',
    'SHARE_DOCUMENT',
    'AI_PROGRESS_ANALYTICS',
    'TEAM_DASHBOARD',
    'GOOGLE_CALENDAR',
    'MANAGE_MEMBERS',
    'CUSTOM_WORKSPACE',
    'PRIORITY_SUPPORT',
]

export const PACKAGE_FEATURE_LABELS = {
    NOTE_LIMIT: 'Số ghi chú',
    DEVICE_LIMIT: 'Số thiết bị',
    TAG_SUBJECT: 'Tag môn học / chủ đề',
    CHECKLIST_BASIC: 'Checklist công việc cơ bản',
    AI_NOTE_FORMAT: 'AI format ghi chú',
    AI_SUMMARY_BASIC: 'Tóm tắt AI cơ bản',
    AI_SUMMARY_ADVANCED: 'Tóm tắt & phân tích AI nâng cao',
    AI_CHAT: 'Hỏi đáp AI với ghi chú / tài liệu',
    AI_ANALYZE: 'AI phân tích tài liệu chuyên sâu',
    AI_AUDIO: 'Ghi chú âm thanh (Whisper AI)',
    DOCUMENT_UPLOAD: 'Upload tài liệu',
    EXTRACT_SCHEDULE: 'AI trích xuất deadline từ ghi chú',
    AI_FLASHCARD: 'Flashcard AI tự động',
    DEADLINE_MANAGEMENT: 'Quản lý deadline thông minh',
    PRIORITY_SUGGESTION: 'Gợi ý ưu tiên công việc',
    EXPORT_FILE: 'Export PDF / Word',
    TEAM_WORK: 'Chia sẻ ghi chú với người khác (VIEW/EDIT)',
    SHARE_DOCUMENT: 'Chia sẻ tài liệu với người khác (VIEW/EDIT)',
    AI_PROGRESS_ANALYTICS: 'Thống kê & điểm tiến độ học tập',
    TEAM_DASHBOARD: 'Dashboard theo dõi nhóm',
    GOOGLE_CALENDAR: 'Tích hợp Google Calendar',
    MANAGE_MEMBERS: 'Admin quản lý thành viên nhóm',
    CUSTOM_WORKSPACE: 'Custom workspace theo nhóm',
    PRIORITY_SUPPORT: 'Ưu tiên hỗ trợ khách hàng',
}

export const ADMIN_PACKAGE_FEATURES = [
    { id: 'TAG_SUBJECT', label: 'Tag môn học / chủ đề / dự án' },
    { id: 'CHECKLIST_BASIC', label: 'Checklist công việc cơ bản' },
    { id: 'AI_NOTE_FORMAT', label: 'AI format ghi chú' },
    { id: 'AI_SUMMARY_BASIC', label: 'Tóm tắt AI cơ bản' },
    { id: 'AI_SUMMARY_ADVANCED', label: 'Tóm tắt & phân tích AI nâng cao' },
    { id: 'AI_CHAT', label: 'Hỏi đáp AI với ghi chú / tài liệu' },
    { id: 'AI_ANALYZE', label: 'AI phân tích tài liệu' },
    { id: 'AI_AUDIO', label: 'Ghi chú âm thanh (Whisper AI)' },
    { id: 'DOCUMENT_UPLOAD', label: 'Upload tài liệu' },
    { id: 'EXTRACT_SCHEDULE', label: 'AI trích xuất deadline từ ghi chú' },
    { id: 'AI_FLASHCARD', label: 'Flashcard AI tự động' },
    { id: 'DEADLINE_MANAGEMENT', label: 'Quản lý deadline & lịch học thông minh' },
    { id: 'PRIORITY_SUGGESTION', label: 'Gợi ý ưu tiên công việc' },
    { id: 'EXPORT_FILE', label: 'Export PDF / Word' },
    { id: 'TEAM_WORK', label: 'Học nhóm & chia sẻ ghi chú theo nhóm' },
    { id: 'SHARE_DOCUMENT', label: 'Chia sẻ tài liệu với người khác' },
    { id: 'AI_PROGRESS_ANALYTICS', label: 'AI phân tích tiến độ học tập' },
    { id: 'TEAM_DASHBOARD', label: 'Dashboard theo dõi nhóm' },
    { id: 'GOOGLE_CALENDAR', label: 'Tích hợp Google Calendar' },
    { id: 'MANAGE_MEMBERS', label: 'Admin quản lý thành viên nhóm' },
    { id: 'CUSTOM_WORKSPACE', label: 'Custom workspace theo nhóm' },
    { id: 'PRIORITY_SUPPORT', label: 'Ưu tiên hỗ trợ khách hàng' },
]