import client from './client'
const adminApi = {
  getStats:         ()           => client.get('/admin/stats'),
  getAiStats:       ()           => client.get('/admin/ai-stats'),
  getUsers:         (params)     => client.get('/admin/users', { params }),
  updateUser:       (id, data)   => client.put(`/admin/users/${id}`, data),
  deleteUser:       (id)         => client.delete(`/admin/users/${id}`),
  getPrompts:       ()           => client.get('/admin/prompts'),
  updatePrompt:     (id, text)   => client.put(`/admin/prompts/${id}`, { promptText: text }),
  broadcast:        (data)       => client.post('/admin/broadcast', data),
  getLandingDraft:  ()           => client.get('/admin/landing'),
  saveLandingDraft: (data)       => client.put('/admin/landing', data),
  publishLanding:   ()           => client.post('/admin/landing/publish'),
  getTransactions:  (params)     => client.get('/admin/transactions', { params }),
  getTransaction:   (id)         => client.get(`/admin/transactions/${id}`),
  getRevenue:       (params)     => client.get('/admin/transactions/revenue', { params }),
  reconcileTransaction: (id)     => client.post(`/admin/transactions/${id}/reconcile`),
  refundTransaction: (id, data)  => client.post(`/admin/transactions/${id}/refund`, data),
  updateTransactionStatus: (id, data) => client.put(`/admin/transactions/${id}/status`, data),
  extendSubscription: (userId, data) => client.post(`/admin/users/${userId}/subscription/extend`, data),
  cancelSubscription: (userId, data) => client.post(`/admin/users/${userId}/subscription/cancel`, data),
    getAdminPackages: () => client.get('/admin/packages'),
    createAdminPackage: (data) => client.post('/admin/packages', data),
    updateAdminPackage: (id, data) => client.put(`/admin/packages/${id}`, data),
    deleteAdminPackage: (id) => client.delete(`/admin/packages/${id}`),
}
export default adminApi
